linters:
  LeadingZero:
    enabled: true
    style: include_zero

  Comment:
    enabled: false

  DeclarationOrder:
    enabled: false

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  Indentation:
    enabled: false

  NameFormat:
    enabled: false

  NestingDepth:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorDepth:
    enabled: false

  SelectorFormat:
    enabled: false

  StringQuotes:
    enabled: false

  UrlFormat:
    enabled: false
